import { Hero } from './hero.interface';



// Generated by https://quicktype.io

export interface SummaryInformationResponse {
    totalHeroes: number;
    strongestHero: Hero;
    smartestHero: Hero;
    heroCount: number;
    villainCount: number;
}

